### ISSUE TITLE
STRETCH Search song 

### ISSUE THREAD

**Issue by yarelismartin** [nss-evening-cohort-26/FE-Hackathon-music-streaming-project#15]
User Story:
User should be able to search a song when on the song.js page. Search by artist name, genre, song name.

Acceptance Criteria:

-Look at the team roster 
https://github.com/yarelismartin/INDIVIDUAL-ASSIGNMENT-Team-Roster/blob/main/components/Search.js

Dependencies:
API getSongs

**Comment by britnay268** [comment]
Done.
